package org.solmix.generator.codegen.datax;

import static org.solmix.generator.api.OutputUtilities.newLine;

import java.util.List;

import org.solmix.generator.api.GeneratedSqlFile;
import org.solmix.generator.api.ProgressCallback;
import org.solmix.generator.config.DomainInfo;
import org.solmix.generator.config.SqlGeneratorInfo;
import org.solmix.generator.config.TableInfo;

public class SqlDropGenerator
{
    protected DomainInfo domain;
    protected List<String> warnings;
    protected ProgressCallback progressCallback;

    public SqlDropGenerator() {
        super();
    }

    public DomainInfo getDomain() {
        return domain;
    }

    public void setDomain(DomainInfo domain) {
        this.domain=domain;
    }


    public List<String> getWarnings() {
        return warnings;
    }

    public void setWarnings(List<String> warnings) {
        this.warnings = warnings;
    }

    public ProgressCallback getProgressCallback() {
        return progressCallback;
    }

    public void setProgressCallback(ProgressCallback progressCallback) {
        this.progressCallback = progressCallback;
    }
    
    public GeneratedSqlFile  generate(){
        SqlGeneratorInfo  sgi = domain.getSqlGeneratorInfo();
        String fileName  ="drop."+ domain.getId()+".sql";
        StringBuilder sb  = new StringBuilder();
        sb.append("/* Domain:[" + domain.getId() + "] ");
        newLine(sb);
        sb.append(" * This Sql Script was generated by Code Generator. ");
        newLine(sb);
        sb.append(" */");
        newLine(sb);
        List<TableInfo> tables = domain.getTableInfos();
        for (TableInfo ti : tables) {
            String tableName = ti.getTableName();
            String remark = ti.getRemark();
            sb.append("/* Table :[" + tableName + "] ,Name:" + remark + "*/");
            newLine(sb);
            sb.append("drop table if exists ").append(tableName).append(";\n");
        }
        GeneratedSqlFile file = new GeneratedSqlFile(sgi.getTargetProject(), sgi.getTargetPackage()+".drop", fileName, sb);
        return file;
        
    }
}
