package org.solmix.generator.codegen.datax;

import static org.solmix.generator.api.OutputUtilities.newLine;

import java.util.List;

import org.solmix.generator.api.GeneratedSqlFile;
import org.solmix.generator.api.ProgressCallback;
import org.solmix.generator.config.DomainInfo;
import org.solmix.generator.config.SqlGeneratorInfo;

public class SqlDropGenerator
{
    protected DomainInfo domain;
    protected List<String> warnings;
    protected ProgressCallback progressCallback;

    public SqlDropGenerator() {
        super();
    }

    public DomainInfo getDomain() {
        return domain;
    }

    public void setDomain(DomainInfo domain) {
        this.domain=domain;
    }


    public List<String> getWarnings() {
        return warnings;
    }

    public void setWarnings(List<String> warnings) {
        this.warnings = warnings;
    }

    public ProgressCallback getProgressCallback() {
        return progressCallback;
    }

    public void setProgressCallback(ProgressCallback progressCallback) {
        this.progressCallback = progressCallback;
    }
    
    public GeneratedSqlFile  generate(){
        SqlGeneratorInfo  sgi = domain.getSqlGeneratorInfo();
        String fileName  ="create."+ domain.getId()+".sql";
        StringBuilder sb  = new StringBuilder();
        sb.append("/* Domain:["+domain.getId()+"] ");
        sb.append("   This Sql Script was generated by Code Generator. */");
        newLine(sb);
        GeneratedSqlFile file = new GeneratedSqlFile(sgi.getTargetProject(), sgi.getTargetPackage(), fileName, sb);
        return file;
        
    }
}
